### ISSUE TITLE
Getting position of tokens in original input stream as metadata ?

### ISSUE THREAD

**Issue by rbarzic** [aphyr/clj-antlr#1]
Hi,

I'm looking a way to find determine the original position of an element of the parser tree (in order to be able to point to the source in case of a semantic error found after analysis of the parse tree). But I don't think it is currently possible with clj-antlr. How difficult would it be to add this information as meta-data in the parse tree ?

**Comment by xsc** [comment]
This could be closed once #6 is released.

**Comment by aphyr** [comment]
Released 0.2.4. :)
