### ISSUE TITLE
A warning about deprecated `multi-hinted-let` is issued even if the user code doesn't use it

### ISSUE THREAD

**Issue by p-himik** [aphyr/clj-antlr#14]
That's because `multi-hinted-let` is a macro that's used by `clj-antlr` itself.

**Comment by willcohen** [comment]
This should have been fixed with #12, but I don't think it's made it into a release yet since no other functionality has really changed since.

**Comment by aphyr** [comment]
I can cut another release if y'all need!

**Comment by willcohen** [comment]
I've been getting around it by just using a git dependency target, but I'd say it's worth a release since it happens every time the library gets used.

**Comment by aphyr** [comment]
OK! I'll go ahead and cut now then. :)

**Comment by willcohen** [comment]
Thanks!
