### ISSUE TITLE
Support load the grammar with separate Lexer & Parser files.

### ISSUE THREAD

**Issue by quan-nh** [aphyr/clj-antlr#8]
Is this library support load grammar files with separate Lexer & Parser, e.g. this xml grammar https://github.com/antlr/grammars-v4/tree/master/xml. If not, there is any workaround for it?

Thanks,

**Comment by aphyr** [comment]
No; it only loads single files at a time. You're welcome to submit a PR though.

**Comment by slifin** [comment]
How do you combine the files? I'm looking at the mysql lexer and parser which are two seperate files

https://github.com/slifin/honeySQL-parser/blob/master/src/sql_translation/core.clj#L7

**Comment by quan-nh** [comment]
this may help, I don't remember what I have done :D https://github.com/tentamen/clj-antlr/commit/bc4afe2ba2885421594e53b99d4ca7f8e2c57838

**Comment by vxe** [comment]
@quan-nh did your PR actually work or was it just a sketch?
@aphyr how much work do you estimate it would take to add this feature, most grammers in the antlr official repo are in the two file format as in the one in particular I'm trying to use https://stackoverflow.com/questions/60408016/how-to-combine-antlr-parser-and-lexer-files

**Comment by aphyr** [comment]
Oh gosh, I've got no idea, but if you want to add it I think that'd be swell!--KyleOn Feb 26, 2020 04:26, vijay edwin <notifications@github.com> wrote:@quan-nh did your PR actually work or was it just a sketch?
@aphyr how much work do you estimate it would take to add this feature, most grammers in the antlr official repo are in the two file format as in the one in particular I'm trying to use https://stackoverflow.com/questions/60408016/how-to-combine-antlr-parser-and-lexer-files

**Comment by ieugen** [comment]
I'll try to make a PR for this in the next few days since I need it for a small project.
@aphyr : Looking forward for your review.
